# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ficheiro_caminho'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheiro',
            name='ficheiro',
            field=models.FileField(default='ficheiros/default.pdf', upload_to='ficheiros/'),
        ),
    ]
