# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ficheiro_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheiro',
            name='ficheiro',
            field=models.FileField(default='settings.MEDIA_ROOT/ficheiros/default.pdf', upload_to='ficheiros/'),
        ),
    ]
